import { integrationPrompt } from "./integration-prompt";
import { snippets } from "./snippets";

export type GuideSearchEntry = {
  href: string;
  page: string;
  section: string;
  id: string;
  text: string;
  code?: string;
};

export const guideSearchIndex: GuideSearchEntry[] = [
  {
    href: "/developers",
    page: "Overview",
    section: "Prerequisites",
    id: "start",
    text: "TypeScript Next.js App Router project, running Postparticle deployment, project ID, and at least one published article. Configure POSTPARTICLE_URL POSTPARTICLE_PROJECT POSTPARTICLE_ORGANIZATION_ID WEBSITE_URL on the website server. Public articles API requires no login, Spaces credentials, or browser cookies.",
  },
  {
    href: "/developers",
    page: "Overview",
    section: "Guide sequence",
    id: "guides",
    text: "Setup API connection, list and filter articles, render article pages and Markdown, create metadata and sitemap, choose cache freshness. API reference documents endpoints. Troubleshooting covers common integration problems.",
  },
  {
    href: "/developers",
    page: "Overview",
    section: "API and troubleshooting",
    id: "references",
    text: "API reference documents endpoints, query limits, response fields, media behavior, and error status codes. Troubleshooting checks connection failures, 404 and 400 responses, stale content, and missing media.",
  },
  {
    href: "/developers",
    page: "Overview",
    section: "Example and reference",
    id: "resources",
    text: "Runnable Next.js example in examples/next-blog, downloadable integration.md reference, optional typed client src/lib/client.ts. No published SDK package.",
  },
  {
    href: "/developers/nextjs/setup",
    page: "Setup",
    section: "Environment variables",
    id: "configuration",
    text: "TypeScript Next.js App Router. app and lib folders can live at repository root or under src. POSTPARTICLE_URL deployment base URL, POSTPARTICLE_PROJECT project ID, WEBSITE_URL public site origin without trailing slash. Set on server, Vercel or hosting provider environment settings, and restart local server after env changes. Install server-only react-markdown remark-gfm.",
    code: '.env.local POSTPARTICLE_URL=https://cms.example.com POSTPARTICLE_PROJECT=demo POSTPARTICLE_ORGANIZATION_ID="<organization-uuid>" WEBSITE_URL=https://journal.example.com npm install server-only react-markdown remark-gfm',
  },
  {
    href: "/developers/nextjs/setup",
    page: "Setup",
    section: "Integrate into an existing project",
    id: "existing-project",
    text: "Copyable AI coding assistant prompt. Inspect existing repository conventions, framework and version, data fetching, routing, styling, metadata. Keep requests server-side. Use public API endpoints only. Preserve caching and handle HTTP errors. Avoid unrelated redesign and invented SDKs.",
    code: integrationPrompt,
  },
  {
    href: "/developers/nextjs/setup",
    page: "Setup",
    section: "Typed fetch helper",
    id: "helper",
    text: "Server-only API helper, TypeScript response types, URLSearchParams, encoded project ID and slug, request-time connection, 60 second Next.js revalidation, 404 maps to notFound, other HTTP and network errors reach error boundary. Types do not validate runtime responses.",
    code: snippets.helper.code,
  },
  {
    href: "/developers/nextjs/setup",
    page: "Setup",
    section: "Layout and styles",
    id: "foundation",
    text: "Add example layout and CSS Modules. Merge metadata into existing layout and keep current website design.",
    code: `${snippets.layout.code}\n${snippets.css.code}`,
  },
  {
    href: "/developers/nextjs/setup",
    page: "Setup",
    section: "Run the example",
    id: "runnable-example",
    text: "Run examples/next-blog from repository root with Postparticle at localhost port 3300, website at localhost port 3301. Publish an article first. npm run example:dev -- --port 3301 and npm run example:build. Integration reference downloadable.",
    code: 'POSTPARTICLE_URL=http://localhost:3300 POSTPARTICLE_PROJECT=demo POSTPARTICLE_ORGANIZATION_ID="<organization-uuid>" WEBSITE_URL=http://localhost:3301 npm run example:dev -- --port 3301',
  },
  {
    href: "/developers/nextjs/articles",
    page: "Article listings",
    section: "Homepage articles",
    id: "recent",
    text: "Fetch three published articles in a Server Component. Results sorted by article date newest first, slug breaks ties. Empty state when no articles are published. Cover image and article links.",
    code: snippets.home.code,
  },
  {
    href: "/developers/nextjs/articles",
    page: "Article listings",
    section: "Search and pagination",
    id: "listing",
    text: "Validate query parameters on the server before API call. Search and tag filters can combine. Changing filters resets pagination. Previous and next links preserve filters and date order. Invalid values show guidance and do not request API. Search max 200 characters, tag max 60 characters, page range 1 to 100000. Clear link resets form.",
    code: `${snippets.filters.code}\n${snippets.filterControls.code}\n${snippets.listing.code}`,
  },
  {
    href: "/developers/nextjs/articles",
    page: "Article listings",
    section: "Listing API",
    id: "queries",
    text: "GET /api/v1/projects/demo/articles. Query q searches title excerpt and Markdown body case-insensitively, maximum 200 characters. tag exact case-insensitive matching max 60. order asc or desc by article date; slug ties. page 1 to 100000. pageSize 1 to 100, default 12. Response items total page pageSize. Published articles only.",
    code: "GET /api/v1/projects/demo/articles?organizationId={organizationId}&q=journey&tag=journal&order=desc&page=1&pageSize=12",
  },
  {
    href: "/developers/nextjs/article-pages",
    page: "Article pages",
    section: "Article route",
    id: "route",
    text: "Create app/blog/[slug]/page.tsx. Fetch by encoded slug with server-only helper. Render published article and generate metadata. App Router params are async.",
    code: snippets.article.code,
  },
  {
    href: "/developers/nextjs/article-pages",
    page: "Article pages",
    section: "Markdown and media",
    id: "markdown",
    text: "react-markdown with skipHtml disables raw HTML; default URL handling rejects unsafe schemes. remark-gfm supports tables and task lists. Published media references resolve to public URLs. coverUrl socialImageUrl. Add alt text. Video references are links unless player added.",
  },
  {
    href: "/developers/nextjs/article-pages",
    page: "Article pages",
    section: "Errors and missing articles",
    id: "errors",
    text: "Missing or unpublished article returns 404 and helper calls notFound. HTTP 400 and 503 and network errors reach error boundary. Add app/error.tsx. Draft changes are not public until publish. Website cache delays updates.",
  },
  {
    href: "/developers/nextjs/metadata-and-caching",
    page: "Metadata and caching",
    section: "Metadata and JSON-LD",
    id: "metadata",
    text: "generateMetadata canonical Open Graph Twitter metadata and Article JSON-LD. seoTitle falls back to title. seoDescription falls back to excerpt. Social image falls back to cover. WEBSITE_URL public website origin. Escape less-than in JSON-LD. Render on server for initial HTML.",
    code: snippets.article.code,
  },
  {
    href: "/developers/nextjs/metadata-and-caching",
    page: "Metadata and caching",
    section: "Sitemap and robots",
    id: "sitemap",
    text: "Sitemap reads 100 articles per API page until every published article is included. robots allows indexing on public website. Do not copy Postparticle workspace noindex headers.",
    code: `${snippets.sitemap.code}\n${snippets.robots.code}`,
  },
  {
    href: "/developers/nextjs/metadata-and-caching",
    page: "Metadata and caching",
    section: "Cache freshness",
    id: "freshness",
    text: "API Cache-Control no-store. Example Next.js server fetch revalidate 60 seconds. Revalidate is interval, later request triggers it, not a delivery guarantee. Browser router and CDN caching can extend delay. Use cache no-store for each current server request; do not combine cache no-store and next.revalidate. Unpublish removes API article but cached pages and public media can remain.",
    code: '{ next: { revalidate: 60 } } { cache: "no-store" } Cache-Control: no-store',
  },
  {
    href: "/developers/api-reference",
    page: "API reference",
    section: "Base URL and endpoints",
    id: "endpoints",
    text: "Public GET endpoints for published articles listing, article slug, and published JSON document key. Base path /api/v1/projects/{projectId}. Encode project ID, slug, document key.",
    code: "GET /api/v1/projects/{projectId}/articles?organizationId={organizationId}\nGET /api/v1/projects/{projectId}/articles/{slug}?organizationId={organizationId}\nGET /api/v1/projects/{projectId}/documents/{key}?organizationId={organizationId}",
  },
  {
    href: "/developers/api-reference",
    page: "API reference",
    section: "Article listing parameters",
    id: "listing-parameters",
    text: "q case-insensitive search title excerpt body max 200. tag exact case-insensitive match max 60. order asc desc articleDate; slug breaks ties. page 1 to 100000, pageSize 1 to 100 default 12. Listing response items total page pageSize.",
    code: "?q=journey&tag=journal&order=desc&page=1&pageSize=12",
  },
  {
    href: "/developers/api-reference",
    page: "API reference",
    section: "Article response fields",
    id: "article-response",
    text: "Article title slug excerpt Markdown body author tags articleDate seoTitle seoDescription createdAt updatedAt publishedAt coverUrl socialImageUrl. Article date YYYY-MM-DD; event timestamps UTC ISO strings. Use SEO fallbacks and socialImageUrl fallback to coverUrl.",
  },
  {
    href: "/developers/api-reference",
    page: "API reference",
    section: "Document response and visibility",
    id: "documents",
    text: "GET documents key. Returns key title tags arbitrary value JSON. Published content only. Drafts trash accounts events private object keys credentials excluded.",
  },
  {
    href: "/developers/api-reference",
    page: "API reference",
    section: "Media references",
    id: "media",
    text: "Documents can contain media:UUID string references. Article Markdown images use ![alt](media:asset-id); video can be [caption](media:asset-id). Publication resolves valid media references into public delivery URLs. Private object keys are not returned.",
    code: '{ "hero": "media:550e8400-e29b-41d4-a716-446655440000" }',
  },
  {
    href: "/developers/api-reference",
    page: "API reference",
    section: "Errors and caching",
    id: "errors-and-cache",
    text: "404 missing or unpublished content. 400 invalid request. 503 storage or configuration failures. API sends Cache-Control no-store. Website selects its own server cache policy.",
    code: "Cache-Control: no-store",
  },
  {
    href: "/developers/troubleshooting",
    page: "Troubleshooting",
    section: "Connection and project errors",
    id: "connection",
    text: "Check POSTPARTICLE_URL deployment origin, reachable from website server, no trailing path. Check POSTPARTICLE_PROJECT ID. Restart local development after changing .env.local. Keep environment variables on server.",
  },
  {
    href: "/developers/troubleshooting",
    page: "Troubleshooting",
    section: "404 article or document",
    id: "not-found",
    text: "Confirm project ID, URL-encoded slug or document key, and publish status. Draft and trashed items are not public. Article slug may have changed. The public API returns only published content.",
  },
  {
    href: "/developers/troubleshooting",
    page: "Troubleshooting",
    section: "400 invalid request",
    id: "bad-request",
    text: "Validate q up to 200 characters, tag up to 60, order asc or desc, page integer 1 to 100000, pageSize integer 1 to 100. Omit unset query parameters and encode path segments.",
  },
  {
    href: "/developers/troubleshooting",
    page: "Troubleshooting",
    section: "503 or network failure",
    id: "service-error",
    text: "503 indicates Postparticle service, storage, or configuration failure. Check deployment health and server logs. Do not expose credentials or retry indefinitely. Handle HTTP and network errors with the site's error boundary.",
  },
  {
    href: "/developers/troubleshooting",
    page: "Troubleshooting",
    section: "Content does not update after publish",
    id: "stale-content",
    text: "API response uses Cache-Control no-store, but website may cache server render, Next.js route, browser router, or CDN. Revalidation interval is not immediate purge; later request triggers revalidation. Choose cache no-store for each request or configure cache invalidation in hosting.",
  },
  {
    href: "/developers/troubleshooting",
    page: "Troubleshooting",
    section: "Image or video is missing",
    id: "media-troubleshooting",
    text: "Publish article after adding media. Check exact media reference and public delivery URL in API response. Use alt text. Markdown video references render as links in example; add an approved player for playback.",
  },
];
